### ISSUE TITLE
Чудесно, но не за начинаещи :)

### ISSUE THREAD

**Issue by Twenkid** [Anarcroth/cpp-tutorials#1]
Чудесни материали, но мисля, че целевата група за която си споменал в началото не съвпада със сложността им. Мисля, че това са статии като за хора, които ползват и харесват С++, които да си припомнят, задълбочат или систематизират знанията. Не и за хора, на които С++ им е труден и неразбираем...

Чувал ли си за DOD - Data Oriented Design?

CppCon 2018: Stoyan Nikolov “OOP Is Dead, Long Live Data-oriented Design”
https://www.youtube.com/watch?v=yy8jQgmhbAU

Какво е FDS-домашна? :) Курсови проекти по програмиране?

**Comment by Anarcroth** [comment]
Причината да направя този проект (и да му сложа такъв етикет) е защото водих лекции за колеги които са минали базовите курсове по програмиране в университета. Беше ми част от задълженията като асистент. То има и презентации към това ама трябва да се обновят... Мерси че му хвърли око :)
Иначе съм гледат тази презентация. Хубава е.

А колкото до това с fds, това беше част от една стара домашна за един курс, но си струваше да се направи като проект.

**Comment by Twenkid** [comment]
OK :)

**Comment by Anarcroth** [comment]
>resolved
